
export const LoginAdminGoogle = async (req, res, next) => {
    try {
        
    } catch (error) {
        res.status(500).json({
            success: false,
            message: ["Internal Server Error". error.message]
        })
    }
}

export const LoginAdmin = async (req, res, next) => {
    try {
        
    } catch (error) {
        res.status(500).json({
            success: false,
            message: ["Internal Server Error". error.message]
        })
    }
}

export const LoginClientGoogle = async (req, res, next) => {
    try {
        
    } catch (error) {
        res.status(500).json({
            success: false,
            message: ["Internal Server Error". error.message]
        })
    }
}

export const LoginClient = async (req, res, next) => {
    try {
        
    } catch (error) {
        res.status(500).json({
            success: false,
            message: ["Internal Server Error". error.message]
        })
    }
}

export const Logout = async (req, res, next) => {
    try {
        
    } catch (error) {
        res.status(500).json({
            success: false,
            message: ["Internal Server Error". error.message]
        })
    }
}